package beat.tycotech.beaton;

/* This class is generated by JADX */
public final class R {

    public static final class color {
        public static final int colorAccent = 2130771968;
        public static final int colorPrimary = 2130771969;
        public static final int colorPrimaryDark = 2130771970;
    }

    public static final class drawable {
        public static final int $ic_launcher_foreground__0 = 2130837504;
        public static final int ic_launcher_background = 2130837505;
        public static final int ic_launcher_foreground = 2130837506;
    }

    public static final class mipmap {
        public static final int ic_launcher = 2130903040;
        public static final int ic_launcher_round = 2130903041;
    }

    public static final class string {
        public static final int app_name = 2130968576;
        public static final int target_package = 2130968577;
    }

    public static final class style {
        public static final int AppTheme = 2131034112;
    }
}
